# This file was generated by GoReleaser. DO NOT EDIT.
cask "icm" do
  name "icm"
  desc "Generate or validate intermodal container markings."
  homepage "https://github.com/mrclmr/icm"
  version "3.2.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "icm"
  manpage "man-pages/icm.1"
  manpage "man-pages/icm-download-owners.1"
  manpage "man-pages/icm-generate.1"
  manpage "man-pages/icm-validate.1"
  bash_completion "completions/icm.bash"
  zsh_completion "completions/icm.zsh"
  fish_completion "completions/icm.fish"

  on_macos do
    on_intel do
      url "https://github.com/mrclmr/icm/releases/download/v#{version}/icm_Darwin_x86_64.tar.gz"
      sha256 "9facc06f822c61f9395cf787e9188bd215fa6df462fdfe463b49efcd4085750b"
    end
    on_arm do
      url "https://github.com/mrclmr/icm/releases/download/v#{version}/icm_Darwin_arm64.tar.gz"
      sha256 "a28d1a094691c3062252d035e5c0e96f355308ad8bfca22acbc5c5349cb674a1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mrclmr/icm/releases/download/v#{version}/icm_Linux_x86_64.tar.gz"
      sha256 "264aefc1709e1bbbb821c62ba3a42ff0e06e59970628f52d6fcee08ab4866e7f"
    end
    on_arm do
      url "https://github.com/mrclmr/icm/releases/download/v#{version}/icm_Linux_arm64.tar.gz"
      sha256 "ad213a7a4bd8866134c7354536be7852ad8d1248741970f0ade7e96d9ecde12f"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/icm"]
  end

  # No zap stanza required
end
