# This file was generated by GoReleaser. DO NOT EDIT.
cask "icm" do
  desc "Generate or validate intermodal container markings."
  homepage "https://github.com/mrclmr/icm"
  version "3.2.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "icm"
  manpage "man-pages/icm.1"
  manpage "man-pages/icm-download-owners.1"
  manpage "man-pages/icm-generate.1"
  manpage "man-pages/icm-validate.1"
  bash_completion "completions/icm.bash"
  zsh_completion "completions/icm.zsh"
  fish_completion "completions/icm.fish"

  on_macos do
    on_intel do
      url "https://github.com/mrclmr/icm/releases/download/3.2.10/icm_Darwin_x86_64.tar.gz"
      sha256 "1d8a6a7006c34ef7cf5dda7ca72c87f324a3a883f0c3391df96ba4ba6400dfdf"
    end
    on_arm do
      url "https://github.com/mrclmr/icm/releases/download/3.2.10/icm_Darwin_arm64.tar.gz"
      sha256 "fa1e1ea8cf957505ed4ab7b5214ff33a6264b9fe26100224af40bcfc0755b2c0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mrclmr/icm/releases/download/3.2.10/icm_Linux_x86_64.tar.gz"
      sha256 "65b4c2ac311518218baacd89989155408a856efa067939a5458be27a75d361c5"
    end
    on_arm do
      url "https://github.com/mrclmr/icm/releases/download/3.2.10/icm_Linux_arm64.tar.gz"
      sha256 "9eba175d2efa23618ea0cbfaafb218754ad608f284f8a5592a150fe81dbe1092"
    end
  end

  conflicts_with formula: [
      "icm",
    ]

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/icm"]
  end

  # No zap stanza required
end
