# This file was generated by GoReleaser. DO NOT EDIT.
cask "w2a" do
  desc "Convert a workout yaml file to audio files."
  homepage "https://github.com/mrclmr/w2a"
  version "0.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "w2a"
  manpage "man-pages/w2a.1"
  bash_completion "completions/w2a.bash"
  zsh_completion "completions/w2a.zsh"
  fish_completion "completions/w2a.fish"
  depends_on formula: [
      "sox",
    ]

  on_macos do
    on_intel do
      url "https://github.com/mrclmr/w2a/releases/download/v0.9.0/w2a_Darwin_x86_64.tar.gz"
      sha256 "dc4e975a2a3addd19a8f8c90b56e03cf985573a4b13053075a2a7f6f5f09dff3"
    end
    on_arm do
      url "https://github.com/mrclmr/w2a/releases/download/v0.9.0/w2a_Darwin_arm64.tar.gz"
      sha256 "5baee5d4aa954b4a07d7afeeeefabf3956db4af62c8325282d9d39dbefb75dd8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mrclmr/w2a/releases/download/v0.9.0/w2a_Linux_x86_64.tar.gz"
      sha256 "1a52abd2d6bef94a03fc121ab41e6d26bcccbdfe4c918a841cda00284d00216c"
    end
    on_arm do
      url "https://github.com/mrclmr/w2a/releases/download/v0.9.0/w2a_Linux_arm64.tar.gz"
      sha256 "8f547f0649d3adaf38948c300f82e197ce397ec7964216e378dcaf47497d476d"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/w2a"]
  end

  # No zap stanza required
end
