# This file was generated by GoReleaser. DO NOT EDIT.
cask "w2a" do
  name "w2a"
  desc "Convert a workout yaml file to audio files."
  homepage "https://github.com/mrclmr/w2a"
  version "0.11.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "w2a"
  manpage "man-pages/w2a.1"
  bash_completion "completions/w2a.bash"
  zsh_completion "completions/w2a.zsh"
  fish_completion "completions/w2a.fish"
  depends_on formula: [
      "sox_ng",
    ]

  on_macos do
    on_intel do
      url "https://github.com/mrclmr/w2a/releases/download/v#{version}/w2a_Darwin_x86_64.tar.gz"
      sha256 "641f202efba8b1bba2adc0d4e7b602f3751a99888c4e96fa63726c48c2079515"
    end
    on_arm do
      url "https://github.com/mrclmr/w2a/releases/download/v#{version}/w2a_Darwin_arm64.tar.gz"
      sha256 "2382da8b204260fe10c1c0a104c9a3bd3b420643d2ef4fa81882408d513b6fef"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mrclmr/w2a/releases/download/v#{version}/w2a_Linux_x86_64.tar.gz"
      sha256 "f81001748b7b56c23c109dd107dc66c6bb2f3b511fe75209f07f62b7fd0b0edb"
    end
    on_arm do
      url "https://github.com/mrclmr/w2a/releases/download/v#{version}/w2a_Linux_arm64.tar.gz"
      sha256 "6495440956744a9488d2e17956d9c31ef1c13ae05724014e8896e0192dc2983c"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/w2a"]
  end

  # No zap stanza required
end
