# This file was generated by GoReleaser. DO NOT EDIT.
cask "w2a" do
  desc "Convert a workout yaml file to audio files."
  homepage "https://github.com/mrclmr/w2a"
  version "0.8.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "w2a"
  manpage "man-pages/w2a.1"
  bash_completion "completions/w2a.bash"
  zsh_completion "completions/w2a.zsh"
  fish_completion "completions/w2a.fish"
  depends_on formula: [
      "sox",
    ]

  on_macos do
    on_intel do
      url "https://github.com/mrclmr/w2a/releases/download/v0.8.0/w2a_Darwin_x86_64.tar.gz"
      sha256 "c8ae3788e3be144110f6364a6177c67d7f76ea0ecf6c67c55aa2c03911ce9b5b"
    end
    on_arm do
      url "https://github.com/mrclmr/w2a/releases/download/v0.8.0/w2a_Darwin_arm64.tar.gz"
      sha256 "ef847e36fefecea6199c9d180800d8f9937788912e8a088ad6afade102367fc6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mrclmr/w2a/releases/download/v0.8.0/w2a_Linux_x86_64.tar.gz"
      sha256 "ba68391674793f72b184a1a83e541a962f4b754283ff46e0bdd3d4a3936b5470"
    end
    on_arm do
      url "https://github.com/mrclmr/w2a/releases/download/v0.8.0/w2a_Linux_arm64.tar.gz"
      sha256 "36029667879b1d2ee2cef5abb1cb0f6abbf1d7e8c1c270a6794047c37500ba68"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/w2a"]
  end

  # No zap stanza required
end
